name: golangci-lint
on:
  pull_request:
    branches: [ '**' ]
    
jobs:
  golangci:
    runs-on: ubuntu-latest

    name: lint
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Checkout code
        uses: actions/checkout@v5

      - name: modVerify
        run: go mod verify

      - name: Get golangci-lint
        run: make tools-golangci-lint

      - name: Run golangci-lint
        run: make lint
