name: gotest

on:
  pull_request:
    branches: ["**"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests with go testsum
        run: make test